# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2023, verbose_name="西暦")),
                ("budget_expense", models.IntegerField(default=0, verbose_name="金額")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="備考"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2023, verbose_name="西暦")),
                ("budget_income", models.IntegerField(default=0, verbose_name="金額")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="備考"
                    ),
                ),
            ],
        ),
    ]
