# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("record", "0001_initial"),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomebudget",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.account",
                verbose_name="口座名",
            ),
        ),
        migrations.AddField(
            model_name="incomebudget",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.category",
            ),
        ),
        migrations.AddField(
            model_name="expensebudget",
            name="himoku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="record.himoku"
            ),
        ),
        migrations.AddConstraint(
            model_name="expensebudget",
            constraint=models.UniqueConstraint(
                fields=("year", "himoku"), name="budget_himoku_unique"
            ),
        ),
    ]
