# Generated by Django 4.2.7 on 2023-11-26 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incomebudget",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
