# Generated by Django 5.0 on 2023-12-28 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0003_remove_incomebudget_category_delete_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="expensebudget",
            name="budget_himoku_unique",
        ),
    ]
