# Generated by Django 5.0.1 on 2024-01-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_remove_expensebudget_budget_himoku_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebudget',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='西暦'),
        ),
        migrations.AlterField(
            model_name='incomebudget',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='西暦'),
        ),
    ]
