# Generated by Django 5.0.8 on 2024-08-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expensebudget_year_alter_incomebudget_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeBudget',
        ),
    ]
