# Generated by Django 6.0 on 2026-01-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_expensebudget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebudget',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='西暦'),
        ),
    ]
