# Generated by Django 6.0 on 2026-01-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_expensebudget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebudget',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
    ]
