# Generated by Django 5.0.8 on 2024-08-16 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='コード')),
                ('item_name', models.CharField(max_length=64, verbose_name='請求項目名')),
                ('alive', models.BooleanField(default=True, verbose_name='有効')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='コード')),
                ('transaction_date', models.DateField(verbose_name='取引月')),
                ('billing_ammount', models.IntegerField(default=0, verbose_name='請求金額')),
                ('comment', models.CharField(blank=True, default='', max_length=64, verbose_name='備考')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
                ('billing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingitem', verbose_name='請求内訳名')),
            ],
        ),
    ]
