# Generated by Django 5.0.8 on 2024-08-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='code',
        ),
    ]
