# Generated by Django 5.0.8 on 2024-08-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_billing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='is_billing',
            field=models.BooleanField(default=True),
        ),
    ]
