# Generated by Django 5.2.4 on 2025-08-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingitem_is_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='billing_ammount',
            new_name='billing_amount',
        ),
    ]
