# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("record", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="ac_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.accountingclass",
                verbose_name="会計区分",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="himoku_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="record.himoku",
                verbose_name="費目名",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="payment_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.paymentcategory",
                verbose_name="支払い区分",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="himoku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.himoku",
                verbose_name="費目名",
            ),
        ),
    ]
