# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_date",
                    models.DateField(blank=True, null=True, verbose_name="月度"),
                ),
                ("amounts", models.IntegerField(default=0, verbose_name="金額")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="備考"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceSheetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(default=0)),
                ("item_name", models.CharField(max_length=32, verbose_name="項目名")),
                ("is_asset", models.BooleanField(default=True, verbose_name="資産項目")),
            ],
        ),
        migrations.CreateModel(
            name="ReportTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="取引月")),
                ("ammount", models.IntegerField(default=0, verbose_name="金額")),
                ("miharai_flg", models.BooleanField(default=False)),
                ("mishuu_flg", models.BooleanField(default=False)),
                ("calc_flg", models.BooleanField(default=True, verbose_name="計算対象")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="摘要"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                ("delete_flg", models.BooleanField(default=False)),
                ("is_netting", models.BooleanField(default=False, verbose_name="相殺処理")),
            ],
        ),
    ]
