# Generated by Django 5.0.1 on 2024-01-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttransaction',
            name='miharai_flg',
        ),
        migrations.RemoveField(
            model_name='reporttransaction',
            name='mishuu_flg',
        ),
    ]
