# Generated by Django 5.0.4 on 2024-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0004_remove_reporttransaction_miharai_flg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttransaction',
            name='is_miharai',
            field=models.BooleanField(default=False, verbose_name='未払い'),
        ),
    ]
