# 通帳監査システム
services:
  passbook:
    # 相対パスでDockerfileのpathを指定。
    build: ./
    # image名:タグ
    image: passbook
    # 起動ユーザを指定する
    user: "${UID}:${GID}"
    # container名
    container_name: passbook
    restart: always
    # ホスト上のdjangoソース/ディレクトリをcode/としてコンテナにマウントする。
    volumes:
      - ../:/code
    # 環境変数TZを設定。
    environment:
      TZ: "Asia/Tokyo"
    # 本番環境 コンテナネットワークだけにポートを公開する場合はexposeするだけ。
    expose:
      - "8700"
    # 共有ネットワークに繋げる。(ネットワークを調べるのは、docker network ls)
    networks:
      - sophiag-network
 
    command: /usr/local/bin/gunicorn passbook.wsgi:application -w 2 -b :8700

networks:
  sophiag-network:
    external: true
