# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=32, verbose_name="口座名")),
                ("branch_number", models.CharField(max_length=10, verbose_name="支店番号")),
                (
                    "account_number",
                    models.CharField(max_length=16, unique=True, verbose_name="口座番号"),
                ),
                ("account_type", models.CharField(max_length=16, verbose_name="口座種類")),
                ("alive", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "start_day",
                    models.DateField(blank=True, null=True, verbose_name="開始日"),
                ),
                (
                    "start_ammount",
                    models.IntegerField(blank=True, null=True, verbose_name="開始残高"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="コード")),
                (
                    "accounting_name",
                    models.CharField(max_length=32, unique=True, verbose_name="会計区分名"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=4, unique=True, verbose_name="金融機関コード"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=64, unique=True, verbose_name="銀行名"),
                ),
                ("alive", models.BooleanField(default=True, verbose_name="有効")),
            ],
        ),
        migrations.CreateModel(
            name="Himoku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(unique=True, verbose_name="コード")),
                ("himoku_name", models.CharField(max_length=64, verbose_name="費目名")),
                ("is_income", models.BooleanField(default=False, verbose_name="入金費目")),
                ("alive", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "aggregate_flag",
                    models.BooleanField(default=True, verbose_name="集計"),
                ),
                ("is_approval", models.BooleanField(default=True, verbose_name="承認必要")),
            ],
        ),
        migrations.CreateModel(
            name="TransferRequester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="振込依頼人名"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="備考"
                    ),
                ),
                (
                    "himoku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.himoku",
                        verbose_name="費目名",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_income", models.BooleanField(default=False, verbose_name="入金flg")),
                ("transaction_date", models.DateField(verbose_name="取引日")),
                ("ammount", models.IntegerField(default=0, verbose_name="金額")),
                (
                    "requesters_name",
                    models.CharField(default="", max_length=64, verbose_name="振込依頼人名"),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=64, verbose_name="摘要"),
                ),
                (
                    "balance",
                    models.IntegerField(blank=True, null=True, verbose_name="残高"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                ("delete_flg", models.BooleanField(default=False)),
                ("calc_flg", models.BooleanField(default=True)),
                ("is_manualinput", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.account",
                        verbose_name="口座名",
                    ),
                ),
            ],
        ),
    ]
