# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("record", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="記録者",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="himoku",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.himoku",
                verbose_name="費目名",
            ),
        ),
        migrations.AddField(
            model_name="himoku",
            name="accounting_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="record.accountingclass",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="record.bank",
                verbose_name="銀行名",
            ),
        ),
        migrations.AddConstraint(
            model_name="himoku",
            constraint=models.UniqueConstraint(
                fields=("himoku_name", "accounting_class"), name="himoku_unique"
            ),
        ),
    ]
