# Generated by Django 5.0 on 2023-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="himoku",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="デフォルト"),
        ),
        migrations.AddConstraint(
            model_name="himoku",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="default_himoku_unique",
            ),
        ),
    ]
