# Generated by Django 5.0.4 on 2024-04-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_claimdata_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdata',
            name='comment',
            field=models.CharField(default='', max_length=64, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='claimdata',
            name='claim_type',
            field=models.CharField(choices=[('未収金', '請求時点未収金一覧'), ('前受金', '請求時点前受金一覧'), ('振替不備', '口座振替不備分')], default='未収金', max_length=4, verbose_name='請求種別'),
        ),
    ]
