# Generated by Django 5.1 on 2024-09-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_claimdata_comment_alter_claimdata_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_billing',
            field=models.BooleanField(default=True, verbose_name='請求項目'),
        ),
    ]
