# Generated by Django 5.1 on 2024-09-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_transaction_is_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimdata',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='ammount',
            new_name='amount',
        ),
    ]
