# Generated by Django 5.1.3 on 2024-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_rename_ammount_claimdata_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_maeukekin',
            field=models.BooleanField(default=False, verbose_name='前受金'),
        ),
    ]
