# Generated by Django 5.1.4 on 2025-01-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_transaction_is_mishuukin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_miharai',
            field=models.BooleanField(default=False, verbose_name='未払金支払い'),
        ),
    ]
