# Generated by Django 5.1.4 on 2025-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_transaction_is_miharai'),
    ]

    operations = [
        migrations.AddField(
            model_name='himoku',
            name='is_community',
            field=models.BooleanField(default=False, verbose_name='町内会'),
        ),
    ]
