# Generated by Django 5.2.4 on 2025-08-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_himoku_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='start_ammount',
            new_name='start_amount',
        ),
    ]
