# Generated by Django 5.2.7 on 2025-10-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_rename_start_ammount_account_start_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='himoku',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='備考'),
        ),
    ]
