# Generated by Django 6.0 on 2026-01-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_alter_himoku_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='himoku',
            name='is_unbilled_income',
            field=models.BooleanField(default=False, verbose_name='請求外収入'),
        ),
    ]
