# Generated by Django 4.2.7 on 2023-11-25 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=32, verbose_name="タイトル")),
                ("description", models.TextField(verbose_name="説明文")),
                ("data_operation", models.BooleanField(default=False)),
                ("alive", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
            ],
        ),
    ]
