# Generated by Django 5.2.8 on 2025-12-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_controlrecord_to_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlrecord',
            name='delete_data_flg',
            field=models.BooleanField(default=False, verbose_name='データ削除'),
        ),
    ]
