# Generated by Django 5.2.11 on 2026-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_controlrecord_delete_data_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='4月始まりの場合、2025年4月〜2026年3月は『2025』年度', unique=True, verbose_name='年度')),
                ('is_locked', models.BooleanField(default=False, help_text='チェックを入れると、この年度のデータは削除・編集不可になります', verbose_name='決算確定（ロック）')),
                ('last_closed_month', models.IntegerField(default=0, help_text='例：9月まで締めた場合は『9』。0は未締め', verbose_name='最終締め月')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '決算・締め状態管理',
                'verbose_name_plural': '決算・締め状態管理',
            },
        ),
    ]
